Is cuda available? False
Number of different initial conditions:  20
['delta', 'delta_omega', 'delta_Id', 'delta_Id_dt'] Variables
[[-0.65, 0.65], [60, 60], [0.01, 0.01], [0.1, 0.1]] Set of values for init conditions
[20, 1, 1, 1] Iterations per value
Shape: (20, 4)
ðŸŸ¡ Solving initial condition 1/20: [-0.4640433328627812, 60, 0.01, 0.1]
âœ… Finished IC 1 successfully.
ðŸŸ¡ Solving initial condition 2/20: [-0.10060589312950463, 60, 0.01, 0.1]
âœ… Finished IC 2 successfully.
ðŸŸ¡ Solving initial condition 3/20: [0.5695894542150984, 60, 0.01, 0.1]
âœ… Finished IC 3 successfully.
ðŸŸ¡ Solving initial condition 4/20: [-0.328493984837594, 60, 0.01, 0.1]
âœ… Finished IC 4 successfully.
ðŸŸ¡ Solving initial condition 5/20: [-0.030801376645483325, 60, 0.01, 0.1]
âœ… Finished IC 5 successfully.
ðŸŸ¡ Solving initial condition 6/20: [0.16848703330580805, 60, 0.01, 0.1]
âœ… Finished IC 6 successfully.
ðŸŸ¡ Solving initial condition 7/20: [0.3292604389731233, 60, 0.01, 0.1]
âœ… Finished IC 7 successfully.
ðŸŸ¡ Solving initial condition 8/20: [-0.1837939691568699, 60, 0.01, 0.1]
âœ… Finished IC 8 successfully.
ðŸŸ¡ Solving initial condition 9/20: [-0.639239924421572, 60, 0.01, 0.1]
Error executing job with overrides: []
Traceback (most recent call last):
  File "/Users/nbhsbgnb/PycharmProjects/PythonProject/PowerPINN/create_dataset_d.py", line 60, in <module>
    main()
  File "/opt/anaconda3/envs/myenv/lib/python3.11/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/opt/anaconda3/envs/myenv/lib/python3.11/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/opt/anaconda3/envs/myenv/lib/python3.11/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/opt/anaconda3/envs/myenv/lib/python3.11/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/opt/anaconda3/envs/myenv/lib/python3.11/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
           ^^^^^^
  File "/opt/anaconda3/envs/myenv/lib/python3.11/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
            ^^^^^^^^^^
  File "/opt/anaconda3/envs/myenv/lib/python3.11/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
        ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/myenv/lib/python3.11/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/opt/anaconda3/envs/myenv/lib/python3.11/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nbhsbgnb/PycharmProjects/PythonProject/PowerPINN/create_dataset_d.py", line 47, in main
    solution = GFL_model.solve_model(init_conditions, modelling_full,flag_for_time)  # Solve the model for the various initial conditions
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nbhsbgnb/PycharmProjects/PythonProject/PowerPINN/src/dataset/create_dataset_functions.py", line 280, in solve_model
    solution = self.solve(init_conditions[i], self.modelling_method, modelling_full)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nbhsbgnb/PycharmProjects/PythonProject/PowerPINN/src/dataset/create_dataset_functions.py", line 241, in solve
    solution = solve_ivp(modelling_full.odequation_gfl, self.t_span, x0, t_eval=self.t_eval)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/myenv/lib/python3.11/site-packages/scipy/integrate/_ivp/ivp.py", line 655, in solve_ivp
    message = solver.step()
              ^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/myenv/lib/python3.11/site-packages/scipy/integrate/_ivp/base.py", line 197, in step
    success, message = self._step_impl()
                       ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/myenv/lib/python3.11/site-packages/scipy/integrate/_ivp/rk.py", line 144, in _step_impl
    y_new, f_new = rk_step(self.fun, t, y, self.f, h, self.A,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/myenv/lib/python3.11/site-packages/scipy/integrate/_ivp/rk.py", line 64, in rk_step
    K[s] = fun(t + c * h, y + dy)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/myenv/lib/python3.11/site-packages/scipy/integrate/_ivp/base.py", line 154, in fun
    return self.fun_single(t, y)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/myenv/lib/python3.11/site-packages/scipy/integrate/_ivp/base.py", line 23, in fun_wrapped
    return np.asarray(fun(t, y), dtype=dtype)
                      ^^^^^^^^^
  File "/Users/nbhsbgnb/PycharmProjects/PythonProject/PowerPINN/src/ode/gfl_models_d.py", line 138, in odequation_gfl
    check_state_sanity(t, x, den)
  File "/Users/nbhsbgnb/PycharmProjects/PythonProject/PowerPINN/src/ode/gfl_models_d.py", line 29, in check_state_sanity
    raise ZeroDivisionError(f"denâ‰ˆ0 at t={t:.4f}, state= {x}, den={d}")
ZeroDivisionError: denâ‰ˆ0 at t=0.1790, state= [-1.21518506e+00  1.05095212e+00  7.27863534e+02  1.42996616e+04], den=-7.682690486010557e-07
