Is cuda available? False
Error executing job with overrides: []
Traceback (most recent call last):
  File "C:\Users\h.liu\PycharmProjects\transfer-Code\My_code\create_dataset.py", line 32, in <module>
    main()
  File "C:\Users\h.liu\AppData\Roaming\Python\Python311\site-packages\hydra\main.py", line 94, in decorated_main
    _run_hydra(
  File "C:\Users\h.liu\AppData\Roaming\Python\Python311\site-packages\hydra\_internal\utils.py", line 394, in _run_hydra
    _run_app(
  File "C:\Users\h.liu\AppData\Roaming\Python\Python311\site-packages\hydra\_internal\utils.py", line 457, in _run_app
    run_and_report(
  File "C:\Users\h.liu\AppData\Roaming\Python\Python311\site-packages\hydra\_internal\utils.py", line 223, in run_and_report
    raise ex
  File "C:\Users\h.liu\AppData\Roaming\Python\Python311\site-packages\hydra\_internal\utils.py", line 220, in run_and_report
    return func()
           ^^^^^^
  File "C:\Users\h.liu\AppData\Roaming\Python\Python311\site-packages\hydra\_internal\utils.py", line 458, in <lambda>
    lambda: hydra.run(
            ^^^^^^^^^^
  File "C:\Users\h.liu\AppData\Roaming\Python\Python311\site-packages\hydra\_internal\hydra.py", line 132, in run
    _ = ret.return_value
        ^^^^^^^^^^^^^^^^
  File "C:\Users\h.liu\AppData\Roaming\Python\Python311\site-packages\hydra\core\utils.py", line 260, in return_value
    raise self._return_value
  File "C:\Users\h.liu\AppData\Roaming\Python\Python311\site-packages\hydra\core\utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\h.liu\PycharmProjects\transfer-Code\My_code\create_dataset.py", line 25, in main
    init_cond = Model.create_init_cond()
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\h.liu\PycharmProjects\transfer-Code\My_code\src\dataset\create_dataset_functions.py", line 61, in create_init_cond
    init_conditions = OmegaConf.load(init_conditions_path)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\h.liu\AppData\Roaming\Python\Python311\site-packages\omegaconf\omegaconf.py", line 189, in load
    with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\h.liu\\PycharmProjects\\transfer-Code\\My_code\\src\\conf\\initial_conditions\\GFL_7th_order\\init_cond1.yaml'
