Is cuda available? False
Number of different initial conditions:  16
['delta', 'delta_omega', 'delta_Id', 'delta_Id_dt'] Variables
[[-0.02, 0.02], [-0.01, 0.01], [-0.01, 0.01], [-0.1, 0.1]] Set of values for init conditions
[2, 2, 2, 2] Iterations per value
Shape: (16, 4)
üü° Solving initial condition 1/16: [-0.0030422399334089703, -0.0036111525259378474, 0.0022654742113172293, 0.07773682108035698]
-0.0036111525259378474
70321.34569560258
0.07773682108035698
-0.0004476245606120345
‚ùå Error with IC 1: [-0.0030422399334089703, -0.0036111525259378474, 0.0022654742113172293, 0.07773682108035698], error: list index out of range
üü° Solving initial condition 2/16: [-0.0030422399334089703, -0.0036111525259378474, 0.0022654742113172293, -0.027039476868272835]
-0.0036111525259378474
70441.73976138407
-0.027039476868272835
0.0009310109387120424
‚ùå Error with IC 2: [-0.0030422399334089703, -0.0036111525259378474, 0.0022654742113172293, -0.027039476868272835], error: list index out of range
üü° Solving initial condition 3/16: [-0.0030422399334089703, -0.0036111525259378474, -0.0005236774314832972, 0.07773682108035698]
-0.0036111525259378474
70847.89157858003
0.07773682108035698
-0.00044395462423992845
‚ùå Error with IC 3: [-0.0030422399334089703, -0.0036111525259378474, -0.0005236774314832972, 0.07773682108035698], error: list index out of range
üü° Solving initial condition 4/16: [-0.0030422399334089703, -0.0036111525259378474, -0.0005236774314832972, -0.027039476868272835]
-0.0036111525259378474
70969.52651924017
-0.027039476868272835
0.0009346808750841483
‚ùå Error with IC 4: [-0.0030422399334089703, -0.0036111525259378474, -0.0005236774314832972, -0.027039476868272835], error: list index out of range
üü° Solving initial condition 5/16: [-0.0030422399334089703, 0.0033764140901274727, 0.0022654742113172293, 0.07773682108035698]
0.0033764140901274727
70326.56311454828
0.07773682108035698
-0.001566457266176846
‚ùå Error with IC 5: [-0.0030422399334089703, 0.0033764140901274727, 0.0022654742113172293, 0.07773682108035698], error: list index out of range
üü° Solving initial condition 6/16: [-0.0030422399334089703, 0.0033764140901274727, 0.0022654742113172293, -0.027039476868272835]
0.0033764140901274727
70446.95985818152
-0.027039476868272835
-0.00018782176685276907
‚ùå Error with IC 6: [-0.0030422399334089703, 0.0033764140901274727, 0.0022654742113172293, -0.027039476868272835], error: list index out of range
üü° Solving initial condition 7/16: [-0.0030422399334089703, 0.0033764140901274727, -0.0005236774314832972, 0.07773682108035698]
0.0033764140901274727
70853.1583629586
0.07773682108035698
-0.0015627873298047399
‚ùå Error with IC 7: [-0.0030422399334089703, 0.0033764140901274727, -0.0005236774314832972, 0.07773682108035698], error: list index out of range
üü° Solving initial condition 8/16: [-0.0030422399334089703, 0.0033764140901274727, -0.0005236774314832972, -0.027039476868272835]
0.0033764140901274727
70974.79600907049
-0.027039476868272835
-0.00018415183048066315
‚ùå Error with IC 8: [-0.0030422399334089703, 0.0033764140901274727, -0.0005236774314832972, -0.027039476868272835], error: list index out of range
üü° Solving initial condition 9/16: [0.0001259920396085648, -0.0036111525259378474, 0.0022654742113172293, 0.07773682108035698]
-0.0036111525259378474
70422.69970755439
0.07773682108035698
-0.0010497799261183682
‚ùå Error with IC 9: [0.0001259920396085648, -0.0036111525259378474, 0.0022654742113172293, 0.07773682108035698], error: list index out of range
üü° Solving initial condition 10/16: [0.0001259920396085648, -0.0036111525259378474, 0.0022654742113172293, -0.027039476868272835]
-0.0036111525259378474
70543.09377333589
-0.027039476868272835
0.00032885557320570867
‚ùå Error with IC 10: [0.0001259920396085648, -0.0036111525259378474, 0.0022654742113172293, -0.027039476868272835], error: list index out of range
üü° Solving initial condition 11/16: [0.0001259920396085648, -0.0036111525259378474, -0.0005236774314832972, 0.07773682108035698]
-0.0036111525259378474
70950.29022380729
0.07773682108035698
-0.001046109989746262
‚ùå Error with IC 11: [0.0001259920396085648, -0.0036111525259378474, -0.0005236774314832972, 0.07773682108035698], error: list index out of range
üü° Solving initial condition 12/16: [0.0001259920396085648, -0.0036111525259378474, -0.0005236774314832972, -0.027039476868272835]
-0.0036111525259378474
71071.92516446742
-0.027039476868272835
0.0003325255095778146
‚ùå Error with IC 12: [0.0001259920396085648, -0.0036111525259378474, -0.0005236774314832972, -0.027039476868272835], error: list index out of range
üü° Solving initial condition 13/16: [0.0001259920396085648, 0.0033764140901274727, 0.0022654742113172293, 0.07773682108035698]
0.0033764140901274727
70427.91714336706
0.07773682108035698
-0.0010034442541431259
‚ùå Error with IC 13: [0.0001259920396085648, 0.0033764140901274727, 0.0022654742113172293, 0.07773682108035698], error: list index out of range
üü° Solving initial condition 14/16: [0.0001259920396085648, 0.0033764140901274727, 0.0022654742113172293, -0.027039476868272835]
0.0033764140901274727
70548.3138870003
-0.027039476868272835
0.0003751912451809509
‚ùå Error with IC 14: [0.0001259920396085648, 0.0033764140901274727, 0.0022654742113172293, -0.027039476868272835], error: list index out of range
üü° Solving initial condition 15/16: [0.0001259920396085648, 0.0033764140901274727, -0.0005236774314832972, 0.07773682108035698]
0.0033764140901274727
70955.55702522663
0.07773682108035698
-0.00099977431777102
‚ùå Error with IC 15: [0.0001259920396085648, 0.0033764140901274727, -0.0005236774314832972, 0.07773682108035698], error: list index out of range
üü° Solving initial condition 16/16: [0.0001259920396085648, 0.0033764140901274727, -0.0005236774314832972, -0.027039476868272835]
0.0033764140901274727
71077.19467133854
-0.027039476868272835
0.0003788611815530568
‚ùå Error with IC 16: [0.0001259920396085648, 0.0033764140901274727, -0.0005236774314832972, -0.027039476868272835], error: list index out of range
/opt/anaconda3/envs/myenv/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/opt/anaconda3/envs/myenv/lib/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/opt/anaconda3/envs/myenv/lib/python3.11/site-packages/numpy/core/_methods.py:206: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/opt/anaconda3/envs/myenv/lib/python3.11/site-packages/numpy/core/_methods.py:163: RuntimeWarning: invalid value encountered in divide
  arrmean = um.true_divide(arrmean, div, out=arrmean,
/opt/anaconda3/envs/myenv/lib/python3.11/site-packages/numpy/core/_methods.py:198: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
Mean time per iteration:  nan  and std:  nan
Time taken to solve the model for 16 initial conditions: 0.0028848648071289062 seconds.
[DEBUG] t_span = (0, 5)
Number of files in the directory:  12
Saved dataset "('GFL_4th_order', 'dataset_v13')".
